version: '3.4'
services:
  app:
    image: updev/daxy
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://user:password@host:3306/daxy